name = "formalgorithms"
description = "Formal proofs in SPARK"
version = "0.1.0-dev"

authors = ["Dinu Blanovschi"]
maintainers = ["Dinu Blanovschi <git@dnbln.dev>"]
maintainers-logins = ["dnbln"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
gnatprove = "^14.1.1"

[[depends-on]]
coroutines = "*"

[[depends-on]]
pcl = "*"

[[pins]]
coroutines = { url='git+https://github.com/pmderodat/ada-generators', subdir='coroutines' }

[[pins]]
pcl = { url='git+https://github.com/pmderodat/ada-generators', subdir='pcl' }
